### ISSUE TITLE
Link to join Slack expired

### ISSUE THREAD

**Issue by dgarcia360** [symbol/symbol-docs#494]
The link to join nem2 Slack recently expired.
Please, contact an administrator to create or reactivate the link.

https://join.slack.com/t/nem2/shared_invite/enQtMzY4MDc2NTg0ODgyLWZmZWRiMjViYTVhZjEzOTA0MzUyMTA1NTA5OWQ0MWUzNTA4NjM5OTJhOGViOTBhNjkxYWVhMWRiZDRkOTE0YmU

![image](https://user-images.githubusercontent.com/9107969/91741580-34765680-ebb5-11ea-9de9-576b0683d593.png)

**Comment by dgarcia360** [comment]
Changed the affected links in this repository. I keep the issue open because the README links from other repos have to be edited.

**Comment by dgarcia360** [comment]
New link: https://join.slack.com/t/nem2/shared_invite/zt-h0ppnjfm-ood2bVW5P8I2RzcMFgbCVw

**Comment by segfaultxavi** [comment]
Updated all links in 3ef7d21.

**Comment by segfaultxavi** [comment]
What this issue should really do is modify the READMEs in all repos to point to the docs's contact page (where the up to date Slack link is), instead of replicating a stale Slack link all over the place.

**Comment by segfaultxavi** [comment]
No more Slack! Only Discord now! And links don't expire!
