### ISSUE TITLE
New style for tabbed code snippets

### ISSUE THREAD

**Issue by segfaultxavi** [symbol/symbol-docs#683]
Current code snippets support multiple languages, but people does not realize it, because the language links do not look like tabs at all:
![image](https://user-images.githubusercontent.com/10949043/128145922-9f1d46f6-ee98-4092-ba58-cb6f811e11c6.png)

A more standard tabs look would help:
![image](https://user-images.githubusercontent.com/10949043/128146138-3725b36f-b376-4d42-bd66-5712601a8135.png)

**Comment by dgarcia360** [comment]
@segfaultxavi They look nice! 👏👏

**Comment by segfaultxavi** [comment]
Haha, thanks! Just some simple CSS adjustments but this had been waiting for too long 😄
