### ISSUE TITLE
Update MongoDB instructions to include the --upgrade -d param 

### ISSUE THREAD

**Issue by orisdorch** [symbol/symbol-docs#753]
Current instructions works for the first run of a node, but an existing node needs to be stopped and restarted with the '--upgrade -d' parameter for changes to the custom_parameters.yml to take effect.. Perhaps a second example targeted to an already operational node?

https://github.com/symbol/symbol-docs/blob/main/source/guides/network/connecting-to-mongodb.rst
https://docs.symbolplatform.com/guides/network/connecting-to-mongodb.html

**CURRENT LANGUAGE**
`To forward its internal port to the host you need to give symbol-bootstrap a custom preset file containing the following lines:

databases:
  - openPort: true
And then use this file when configuring symbol-bootstrap, for example:

symbol-bootstrap start -p testnet -a dual -c custom_parameters.yml
This will make the database’s TCP port 27017 accessible from the host so be careful, and only use this feature for development purposes.`

**Note from cryptoBeliever** 
`cryptoBeliever —
First you should add to your custom preset:
databases:
        - openPort: true

Next to apply configuration you should start node with --upgrade flag.
symbol-bootstrap start -p testnet -a dual -c custom-preset.yml --upgrade -d

Works for me. In generated docker-compose ports section is added after this operation:
ports:
            - '27017:27017'

Better to not modify compose manually because with next --upgrade it will be overwritten. `

**Comment by orisdorch** [comment]
See https://github.com/symbol/symbol-docs/pull/754

**Comment by segfaultxavi** [comment]
Better link the Issue with the Pull Request using the menu on the right ("Linked pull requests") instead of a comment. In this way GitHub closes the issue when the PR lands, among other nice things.

**Comment by orisdorch** [comment]
> Better link the Issue with the Pull Request using the menu on the right ("Linked pull requests") instead of a comment. In this way GitHub closes the issue when the PR lands, among other nice things.

I don't believe I have the required permission for this.
