### ISSUE TITLE
Issue 0

### ISSUE THREAD

**Issue by ghost-2014** [symbol/symbol-docs#778]
@0x6861746366574

If you simply delete a post of mine that does not meet your expectations, then please also delete all other posts in other areas, by me. Easy to find under ghost. 
Are just simple contributions, but for the sake of completeness ....

Thank you very much!

**Comment by 0x6861746366574** [comment]
@ghost-2014 Your post was deleted because it's not an issue - it's just a complaint. Please follow the standard-issue format, or you'll be banned from the GitHub organisation entirely. This is your *second* warning.
