### ISSUE TITLE
node unhealth

### ISSUE THREAD

**Issue by ricewang666** [symbol/symbol-docs#935]
{
  "code": "ServiceUnavailable",
  "message": "connection failed"
}

**Comment by ricewang666** [comment]
hi can you help me

**Comment by Wayonb** [comment]
Hi, For faster reply to your issues please to join discord to request help.  - https://discord.com/channels/856325968096133191/862674505193488415

The error seems like your catapult server is down.  What does ``docker ps -a`` shows?  Post this output to discord.

**Comment by ricewang666** [comment]
@Wayonb i slove it ,thanks
