### ISSUE TITLE
Multisign issue

### ISSUE THREAD

**Issue by Arkdell12** [symbol/symbol-docs#936]
Can you help me with the link to download the Trust wallet on my pc. I have the problem of multisign and i cant withdraw my funds.

**Comment by Arkdell12** [comment]
I have a problem of a scammer who gave me acess to a teust wallet but the
wallet needs multisign to withdraw.

**Comment by cryptoBeliever** [comment]
@Arkdell12 Trust wallet is not supporting NEM or Symbol. Not sure why you created an issue here. If you know a scammer contacted you, then you should ignore such messages and ban him before you will do something that will cause your coins lost.

**Comment by Arkdell12** [comment]
Thanks for your reply.

**Comment by Arkdell12** [comment]
But is it possible to withdraw from it.
